### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by rdbende** [tukaan/tukaan#107]

**Comment by rdbende** [comment]
Lol, accident

**Comment by Moosems** [comment]
You added notifications?

**Comment by rdbende** [comment]
Yes, but only on Linux. On macOS it's a bit more complicated.

**Comment by Moosems** [comment]
Aww dang it. That would have been so useful

**Comment by sumeshir26** [comment]
I think its possible on Windows as well. There is a module called Win10Toast on PyPi that does this

**Comment by Moosems** [comment]
It's possible on Mac using osascript. Look [here](https://stackoverflow.com/a/41318195/17053202) and in the comments on it

**Comment by rdbende** [comment]
I opened this issue accidentally from #38. I do plan to implement notifications for Windoze and mac, but I track it in #38.

**Comment by Moosems** [comment]
Oh

**Comment by rdbende** [comment]
No problem! 
It's just that I'd rather not have two separate issues on kinda the same topic, 'cause later it would be harder to find the info I'm looking for.

**Comment by Moosems** [comment]
Makes sense!
