### ISSUE TITLE
Upload to pypi soon

### ISSUE THREAD

**Issue by Moosems** [tukaan/tukaan#116]
Hasn't been updated in a while and I'd like to try some of the new features

**Comment by rdbende** [comment]
Indeed. There's been quite a few braking changes since v0.1.3

![image](https://user-images.githubusercontent.com/77941087/205749946-45508503-7dd1-4f96-a353-acb9041afed6.jpeg)

Next version should be v0.2.0

**Comment by Moosems** [comment]
Correct and I'd be willing to devote some time to that
