### ISSUE TITLE
Window not shown

### ISSUE THREAD

**Issue by littlewhitecloud** [tukaan/tukaan#143]
### Describe the bug

This is a wonderful project!
I am writing down an example and running it but it failed.
```
import tukaan

app = tukaan.App(name = "Test!")
app.run()
```

### Expected behavior

Expected a window.
But
Show nothing.

BTW, can add some examples too?

### Operating system

Windows 10

### Extra details about your system

/

**Comment by littlewhitecloud** [comment]
Version:```tukaan==0.2.1```
It won't happened on ```tukaan==0.1.3```

**Comment by littlewhitecloud** [comment]
nevermind, the example was too old.

**Comment by rdbende** [comment]
Whoaaa! Thanks for trying out Tukaan!
If you have any more issues or ideas, feel free to open a issue or a discussion, I'd love to hear some feedback ❣️

So. You're only creating an app context, which isn't enough in Tukaan, you also need to create the main window.

```py
import tukaan

app = tukaan.App(name="My first app")

window = tukaan.MainWindow(title="Hello World!")

greeting_label = tukaan.Label(window, text="Hello World!")
greeting_label.grid()

app.run()
```

You can see some stuff at https://tukaan.github.io/, although it indeed isn't much, and might be outdated.

**Comment by littlewhitecloud** [comment]
> Whoaaa! Thanks for trying out Tukaan! If you have any more issues or ideas, feel free to open a issue or a discussion, I'd love to hear some feedback ❣️
> 
> So. You're only creating an app context, which isn't enough in Tukaan, you also need to create the main window.
> 
> ```python
> import tukaan
> 
> app = tukaan.App(name="My first app")
> 
> window = tukaan.MainWindow(title="Hello World!")
> 
> greeting_label = tukaan.Label(window, text="Hello World!")
> greeting_label.grid()
> 
> app.run()
> ```
> 
> You can see some stuff at https://tukaan.github.io/, although it indeed isn't much, and might be outdated.

Thank you, I will try it!

**Comment by littlewhitecloud** [comment]
BTW, how can I use blur?
Sorry for interrupting you so much.

**Comment by rdbende** [comment]
You can use this:

```py
from tukaan.enums import WindowBackdropType

window.set_backdrop_effect(WindowBackdropType.Acrylic, dark=True)
```

However, this functionality will be remove in the next release, and will be moved to a separate package.

**Comment by littlewhitecloud** [comment]
Thank you
