### ISSUE TITLE
The first example in the readme fails with "TypeError: grid() got an unexpected keyword argument 'column'"

### ISSUE THREAD

**Issue by insolor** [tukaan/tukaan#37]
The problem is in the following line:
```
self.button.layout.grid(row=0, column=0, margin=(1, 2, 3, 4))
```
There is no `column` parameter in the `Grid.grid` method, there is `col` instead.

But I wonder, isn't it better to use full names like "column" or "columnspan"?

**Comment by rdbende** [comment]
LOL, I just haven't tried any of the examples, so yes.

I named it `col` and `colspan` because `column(span)` is way longer, much longer than I would like to type in each line. Though now that cells work well, I'll consider renaming them.

**Comment by insolor** [comment]
I think I'm a bit out of context, what cells do you mean?

**Comment by rdbende** [comment]
When you do this:

```python
frame.layout.grid_cells = [
    ["button", "button", "button", "other", "asdf"],
    ["label", "entry", "rowspan"],
    ["colspan", "colspan", "rowspan"],
]

tukaan.Button(frame, text="Button").layout.cell = "button"
tukaan.Label(frame, text="Label").layout.cell = "label"
tukaan.Entry(frame).layout.cell = "entry"
```

Specify the cell layout with lists and strs, and then apply it to the widget. So you don't have to set column, row, columnspan, and rowspan explicitly.

**Comment by insolor** [comment]
Ok, got it
