### ISSUE TITLE
Publish Tukaan to Pypi

### ISSUE THREAD

**Issue by sumeshir26** [tukaan/tukaan#46]

**Comment by rdbende** [comment]
I don't want to add it to PyPi yet, because there is still a lot to do, but I'll keep this issue open until it's done.

**Comment by im-coder-lg** [comment]
Hiya guys(yeah I know @sumeshir26 and @not-nef, I work with them). So how do you import Tukaan? Is it like cloning the repo and adding it to a project?

**Comment by rdbende** [comment]
Currently yes.

**Comment by not-nef** [comment]
> Hiya guys(yeah I know @sumeshir26 and @not-nef, I work with them). So how do you import Tukaan? Is it like cloning the repo and adding it to a project?

You can add simply use tukaan by putting the `tukaan` Folder in `%LOCALAPPDATA%\Programs\Python\Python310\Lib\site-packages`. Now you can use it like any other module! @im-coder-lg

**Comment by im-coder-lg** [comment]
Hmm, will try that. I'm also working in making the formatting workflow better. Will make the PR when I am free.

**Comment by not-nef** [comment]
> Hmm, will try that. I'm also working in making the formatting workflow better. Will make the PR when I am free.

I think this is the wrong repo 😅

**Comment by im-coder-lg** [comment]
It's the right repo.

**Comment by not-nef** [comment]
I mean we shouldn't talk about it here

**Comment by im-coder-lg** [comment]
I meant that here, the checks are merely checks. Would it be better if it formatted and optionally concatenated the code if it detects that the code isn't formatted?

**Comment by not-nef** [comment]
idk what u talkin bout

**Comment by im-coder-lg** [comment]
me: _what_
I am talking about enhancing the workflow. Just need ideas.

**Comment by not-nef** [comment]
But why dont we speak about it in the timerx repo?

**Comment by im-coder-lg** [comment]
'cause I am thinking of doing it here too. Look, right now, @rdbende has to do formatting locally, so what I am telling is, I have noticed him using a KDE Linux machine, so if he allows, I'll make a simple SH file that formats and optionally(I don't think I'll add it, maybe to a very important file exclusively) concatenates the code to show it was formatted.
