### ISSUE TITLE
Allow wildcard imports? 🤔

### ISSUE THREAD

**Issue by Moosems** [tukaan/tukaan#78]
When I create an app with tkinter I normally will start the file with `from tkinter import *` so it gets rid of the hassle of importing labels and buttons and whatnot. We need to make that compatible and work with Tukaan. Great job on the release by the way!

**Comment by rdbende** [comment]
Well, the thing is that I **really** hate star imports in Python. It's almost always a bad and lazy thing to do. It bloats the global namespace, and makes the code less readable.
https://github.com/tukaan/tukaan/blob/228e7da094eeaff942360553dd0715497440002c/tukaan/__init__.py#L1
I deliberately made such imports impossible, to prevent people from making such bad things while using Tukaan. I wouldn't recommend anyone to do star imports, especially with Tkinter, as you mentioned.
In tkinter you have two different widget sets, and if you do 
```python
from tkinter import *
from tkinter.ttk import *
```
then how do you know, which widget comes from which widget set? Therefore I **really** recommend everyone to do this instead, where you can use both plain tk and themed widgets.
```python
import tkinter as tk  # So it's short, and you don't have to type too much
from tkinter import ttk  # Get themed widgets

window = tk.Tk()

non_themed_btn = tk.Button(window)
themed_btn = ttk.Button(window)
```

If you know the [Zen of Python](https://peps.python.org/pep-0020/) you know, that `Explicit is better than implicit` and that `readability counts`, and star imports procide neither of those.
I'm currently on a touch device, so explaining this is kinda a pain for me, but here's a [great post](https://s16h.medium.com/importing-star-in-python-88fe9e8bd4d2) that explains it.
Anyways I'd stick with `import tukaan` and `from tukaan import SomeThing`, it isn't that exhaustive.

**Comment by Moosems** [comment]
@rdbende Understood and noted. Thanks for the advice by the way
